name: Setup Protofetch
description: |
  Installs protofetch, configures git credentials for a Github user with cross-repo read privileges

inputs:
  cross-repo-username:
    description: Username of a Github user with cross-repository read privileges
    required: true
  cross-repo-token:
    description: Access token of a Github user with cross-repository read privileges
    required: true

runs:
  using: composite
  steps:
    - name: Install protofetch
      shell: bash
      run: |-
        TAR_FILE="protofetch_x86_64-unknown-linux-musl.tar.gz"
        wget --quiet "https://github.com/knox-networks/protofetch/releases/download/knox-release-2/protofetch_x86_64-unknown-linux-musl.tar.gz"
        tar -xzvf $TAR_FILE --strip-components 1
        sudo mv protofetch /usr/local/bin

    - name: Setup git credential helper
      shell: bash
      run: |-
        git config --global credential.helper '!f() { echo username=${{ inputs.cross-repo-username }}; echo password=${{ inputs.cross-repo-token }}; };f'


